name: Node

on:
  - push

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build
        run: |
          make install
          make publish
        env:
          CI: true
      - name: Run linter
        run: |
          make lint
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.4.0
        env:
          CC_TEST_REPORTER_ID: b32b641fa5fb3fe95ea66cf99eb84c202e07f1dbc27ca9133d91049d9e0947be
        with:
          coverageCommand: make test-coverage
          debug: true
