name: Node

on:
  - push

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build
        run: |
          make install
          make publish
        env:
          CI: true
     
      - name: Run linter
        run: make lint

      - name: Run tests
        run: make test
